# Generated by Django 5.2.4 on 2025-08-19 19:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "000X_split_lista_tecnica"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalbom",
            name="produto_pai",
        ),
        migrations.AddField(
            model_name="historicalbom",
            name="lista_pai",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.listatecnica",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="componente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usos",
                to="core.produto",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="lista_pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="core.listatecnica",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="quantidade",
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name="historicalbom",
            name="quantidade",
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name="historicalproduto",
            name="codigo",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalproduto",
            name="codigo_fabricante",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalproduto",
            name="estoque",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="historicalproduto",
            name="fabricante",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalproduto",
            name="lead_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historicalproduto",
            name="nome",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalproduto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("componente", "Componente"),
                    ("materia_prima", "Matéria-Prima"),
                ],
                default="componente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduto",
            name="unidade",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="listatecnica",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo_fabricante",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="produto",
            name="estoque",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="produto",
            name="fabricante",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="produto",
            name="lead_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("componente", "Componente"),
                    ("materia_prima", "Matéria-Prima"),
                ],
                default="componente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="unidade",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.CreateModel(
            name="HistoricalListaTecnica",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=50)),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SERIE", "Série"),
                            ("SISTEMA", "Sistema"),
                            ("CONJUNTO", "Conjunto"),
                            ("SUBCONJUNTO", "Subconjunto"),
                            ("ITEM", "Item"),
                        ],
                        default="CONJUNTO",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listatecnica",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical lista tecnica",
                "verbose_name_plural": "historical lista tecnicas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
