# Generated by Django 5.2.4 on 2025-08-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_remove_historicalbom_produto_pai_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("componente", "Componente"),
                    ("materia_prima", "Matéria-Prima"),
                ],
                default="produto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listatecnica",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("SERIE", "Série"),
                    ("SISTEMA", "Sistema"),
                    ("CONJUNTO", "Conjunto"),
                    ("SUBCONJUNTO", "Subconjunto"),
                    ("ITEM", "Item"),
                ],
                default="CONJUNTO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("componente", "Componente"),
                    ("materia_prima", "Matéria-Prima"),
                ],
                default="produto",
                max_length=20,
            ),
        ),
    ]
