# Generated by Django 5.2.4 on 2025-07-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalbom_historicalordemproducao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('produto', 'Produto Acabado'), ('materia_prima', 'Matéria-Prima'), ('lista', 'Lista Técnica (BOM)')], default='produto', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='lead_time',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='HistoricalProduto',
        ),
    ]
