# Generated by Django 5.2.4 on 2025-08-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_historicalproduto_tipo_alter_listatecnica_tipo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalordemproducao",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="ordemproducao",
            name="produto",
        ),
        migrations.AddField(
            model_name="historicalordemproducao",
            name="lista",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.listatecnica",
            ),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="lista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens",
                to="core.listatecnica",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("componente", "Componente"),
                    ("materia_prima", "Matéria-Prima"),
                ],
                default="componente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("componente", "Componente"),
                    ("materia_prima", "Matéria-Prima"),
                ],
                default="componente",
                max_length=20,
            ),
        ),
    ]
