# Generated by Django 5.2.4 on 2025-08-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_produto_tipo_alter_produto_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="unidade",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
