# Generated by Django 5.2.4 on 2025-08-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_historicalordemproducao_produto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemproducao",
            name="lista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens",
                to="core.listatecnica",
            ),
        ),
    ]
