# Generated by Django 5.2.4 on 2025-08-02 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_produto_unidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="estoque",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="lead_time",
        ),
        migrations.AddField(
            model_name="bom",
            name="comentario",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bom",
            name="ponderacao",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalbom",
            name="comentario",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbom",
            name="ponderacao",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo_fabricante",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo_gmao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="fabricante",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="serie",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bom",
            name="componente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pais",
                to="core.produto",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="produto_pai",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filhos",
                to="core.produto",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="quantidade",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="historicalbom",
            name="quantidade",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=255),
        ),
    ]
