# Generated by Django 5.2.4 on 2025-08-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_historicalproduto"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduto",
            name="codigo_fabricante",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalproduto",
            name="fabricante",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalproduto",
            name="unidade",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo_fabricante",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="fabricante",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="unidade",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
