# Generated by Django 5.2.4 on 2025-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_ordemproducao_lista"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalordemproducao",
            name="atualizado_em",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalordemproducao",
            name="criado_em",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ordemproducao",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
