# Generated by Django 5.2.4 on 2025-08-15 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_historicalproduto_codigo_fabricante_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduto",
            name="tipo",
            field=models.CharField(
                choices=[("produto", "Componente"), ("materia_prima", "Matéria-Prima")],
                default="produto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[("produto", "Componente"), ("materia_prima", "Matéria-Prima")],
                default="produto",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ListaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SERIE", "SÉRIE"),
                            ("SISTEMA", "SISTEMA"),
                            ("CONJUNTO", "CONJUNTO"),
                            ("SUB-CONJUNTO", "SUB-CONJUNTO"),
                            ("ITEM", "ITEM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filhos",
                        to="core.listatecnica",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "codigo"],
            },
        ),
    ]
