# Generated by Django 5.2.4 on 2025-08-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_historicalproduto_codigo_fabricante_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SERIE", "Série"),
                            ("SISTEMA", "Sistema"),
                            ("CONJUNTO", "Conjunto"),
                            ("SUBCONJUNTO", "Sub-Conjunto"),
                            ("ITEM", "Item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
