# Generated by Django 5.2.4 on 2025-08-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_historicalordemproducao_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="sublista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usos_como_sublista",
                to="core.listatecnica",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="componente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usos",
                to="core.produto",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="lista_pai",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="core.listatecnica",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="quantidade",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.DeleteModel(
            name="HistoricalBOM",
        ),
    ]
