# Generated by Django 5.2.4 on 2025-08-21 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_bom_sublista_alter_bom_componente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="comentarios",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bom",
            name="ponderacao_operacao",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("1.0"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="quant_ponderada",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0"), editable=False, max_digits=10
            ),
        ),
    ]
