# Generated by Django 5.2.4 on 2025-08-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_listatecnica"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listatecnica",
            options={
                "ordering": ["codigo"],
                "verbose_name": "Lista Técnica",
                "verbose_name_plural": "Listas Técnicas",
            },
        ),
    ]
