# Generated by Django 5.2.4 on 2025-08-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_historicalproduto_tipo_alter_produto_tipo_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bom",
            constraint=models.UniqueConstraint(
                fields=("produto_pai", "componente"), name="uniq_pai_componente"
            ),
        ),
    ]
