# Generated by Django 5.2.4 on 2025-08-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_historicalproduto"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduto",
            name="estoque",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="produto",
            name="estoque",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
