# Generated by Django 5.2.4 on 2025-08-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_bom_comentarios_bom_ponderacao_operacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bom",
            name="ponderacao_operacao",
            field=models.DecimalField(decimal_places=4, default=100, max_digits=7),
        ),
    ]
