# Generated by Django 5.2.4 on 2025-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_historicalproduto_estoque_produto_estoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduto",
            name="lead_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="produto",
            name="lead_time",
            field=models.IntegerField(default=0),
        ),
    ]
