# Generated by Django 5.2.4 on 2025-08-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_listatecnica_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listatecnica",
            options={"ordering": ["codigo"]},
        ),
        migrations.AddField(
            model_name="listatecnica",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filhos",
                to="core.listatecnica",
            ),
        ),
        migrations.AlterField(
            model_name="listatecnica",
            name="nome",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="listatecnica",
            name="observacoes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="listatecnica",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("SERIE", "Série"),
                    ("SISTEMA", "Sistema"),
                    ("CONJUNTO", "Conjunto"),
                    ("SUBCONJUNTO", "Subconjunto"),
                    ("ITEM", "Item"),
                ],
                max_length=20,
            ),
        ),
    ]
