# Generated by Django 5.2.4 on 2025-08-22 18:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_bom_ponderacao_operacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bom",
            name="quant_ponderada",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                editable=False,
                max_digits=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="bom",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("componente__isnull", False), ("sublista__isnull", True)),
                    models.Q(("componente__isnull", True), ("sublista__isnull", False)),
                    _connector="OR",
                ),
                name="bom_xor_componente_sublista",
            ),
        ),
        migrations.AddConstraint(
            model_name="bom",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ponderacao_operacao__gte", 0), ("ponderacao_operacao__lte", 100)
                ),
                name="bom_ponderacao_0_100",
            ),
        ),
    ]
