# Generated by Django 5.2.4 on 2025-08-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_historicalproduto_lead_time_produto_lead_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("codigo", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="historicalproduto",
            name="codigo_fabricante",
        ),
        migrations.RemoveField(
            model_name="historicalproduto",
            name="fabricante",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="codigo_fabricante",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="fabricante",
        ),
    ]
