# Generated by Django 5.2.4 on 2025-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_bom_quant_ponderada_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listatecnica",
            options={},
        ),
        migrations.AlterField(
            model_name="historicallistatecnica",
            name="codigo",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="listatecnica",
            name="codigo",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=50
            ),
        ),
        migrations.AddConstraint(
            model_name="listatecnica",
            constraint=models.UniqueConstraint(
                fields=("nome", "tipo"), name="uniq_lista_tecnica_nome_tipo"
            ),
        ),
    ]
