# Generated by Django 5.2.4 on 2025-08-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_listatecnica_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduto",
            name="codigo",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
