# Generated by Django 5.2.4 on 2025-09-09 15:18

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_historicalproduto_codigo_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='ponderacao_operacao',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=7, validators=[core.validators.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='bom',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12, validators=[core.validators.validate_quantidade_bom]),
        ),
        migrations.AlterField(
            model_name='historicalordemproducao',
            name='quantidade',
            field=models.IntegerField(validators=[core.validators.validate_positive_decimal]),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, validators=[core.validators.validate_codigo_produto]),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='estoque',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='lead_time',
            field=models.IntegerField(default=0, validators=[core.validators.validate_lead_time]),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='quantidade',
            field=models.IntegerField(validators=[core.validators.validate_positive_decimal]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[core.validators.validate_codigo_produto]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='lead_time',
            field=models.IntegerField(default=0, validators=[core.validators.validate_lead_time]),
        ),
    ]
