# Generated by Django 5.2.4 on 2025-09-09 16:20

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bom_ponderacao_operacao_alter_bom_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[core.validators.validate_quantidade_bom])),
                ('ponderacao', models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[core.validators.validate_percentage], verbose_name='Ponderação (%)')),
                ('comentarios', models.TextField(blank=True, default='')),
                ('componente', models.ForeignKey(limit_choices_to={'tipo': 'componente'}, on_delete=django.db.models.deletion.CASCADE, related_name='em_listas', to='core.produto')),
                ('lista_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_vinculados', to='core.listatecnica')),
            ],
            options={
                'verbose_name': 'Componente em Lista Técnica',
                'verbose_name_plural': 'Componentes em Listas Técnicas',
                'unique_together': {('lista_pai', 'componente')},
            },
        ),
        migrations.CreateModel(
            name='BOMSublista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublistas_vinculadas', to='core.listatecnica')),
                ('sublista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_vinculando', to='core.listatecnica')),
            ],
            options={
                'verbose_name': 'Vínculo de Sublista',
                'verbose_name_plural': 'Vínculos de Sublistas',
                'unique_together': {('lista_pai', 'sublista')},
            },
        ),
    ]
