# Generated by Django 5.2.4 on 2025-09-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bomcomponente_bomsublista'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponente',
            name='tipo_revisao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
